service: webhook-relay

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  stage: prod
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
      Resource:
        Fn::GetAtt:
          - WebhookQueue
          - Arn
  environment:
    # Please replace __GITHUB_WEBHOOK_SECRET__ with a secret random string 
    # and put it in the GitHub webhook page as well.
    GITHUB_WEBHOOK_SECRET: "__GITHUB_WEBHOOK_SECRET__"
    QUEUE_URL: !Ref WebhookQueue

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  webhook:
    handler: bin/webhook
    events:
      - http:
          path: ghprbhook
          method: post

resources:
  Resources:
    WebhookQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: github-webhook
